name = "saat"
compatibility_date = "2024-09-01"

[site]
bucket = "."

[vars]
PAGES_BASIC_AUTH_PASSWORD = "change-me-strong-password"

[[kv_namespaces]]
binding = "SAAT_KV"
id = "ac04a8d3f11a4e58b399cea5765e0e46"
